### ISSUE TITLE
Installation procedure seems to be broken again

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#97] opened 2015-12-02 00:06 UTC
If you follow the installation instructions, you will get to the point where you create the superuser. This part will work, so access to the database works. This can be verified by the UI denying you access to the admin backend, when you enter a wrong password.

Correct login as the super user or as a new user using the Open ID provider will fail with the following error though:

"unable to open database file"

The DB config in the opensubmit.settings seems to be fine (I tried both, the location from the installation log (= submit.db) and this one):

DATABASES 	

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/var/lib/opensubmit/database.sqlite',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'Europe/Berlin',
             'USER': ''}}

**Comment by Feinbube** [comment] 2015-12-02 00:06
Can someone cross-check this?

**Comment by troeger** [comment] 2015-12-02 09:22
Reproducible in Vagrant. 

The reason seems to be the missing absolute path for DATABASE_NAME in the settings.ini template file. This leads to the generation of the database file in the current directory, when you run `opensubmit-web`, which definitely makes no sense for the web server. The command-line tool will work as long as you don't leave that directory.

After changing DATABASE_NAME to an absolute path, everything worked in Vagrant.

Generally speaking, these things happen when the SQLite file sits at some place where the administrating user has rights, but not the web server.

The question is if we only fix `settings.ini.template`, or if the configure script somehow should protect you from that.

**Comment by Feinbube** [comment] 2015-12-07 11:48
I used the absolute path (/var/lib/opensubmit/database.sqlite), though.

As user rights are the problem, the installer (configure script) should either fix them or inform the user that there is a problem and what needs to be done exactly.

**Comment by troeger** [comment] 2016-03-08 11:12
Fixed with 8af87b2e2920cf2968aa357d4525e33f52436223.

**Closed by troeger** 2016-03-08 11:12 UTC
Labels: bug, question
