### ISSUE TITLE
Download of valdiator.zip and grading.zip in teacher backend (assingment details) is broken

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#72] opened 2015-11-03 15:45 UTC
Request Method:	GET
Request URL:	https://www.dcl.hpi.uni-potsdam.de/submit/files/testscripts/validate_BiADTr2.zip

Using the URLconf defined in opensubmit.urls, Django tried these URL patterns, in this order:
^$ [name='index']
^logout/$ [name='logout']
^dashboard/$ [name='dashboard']
^details/(?P<subm_id>\d+)/$ [name='details']
^assignments/(?P<ass_id>\d+)/new/$ [name='new']
^withdraw/(?P<subm_id>\d+)/$ [name='withdraw']
^update/(?P<subm_id>\d+)/$ [name='update']
^course/(?P<course_id>\d+)/gradingtable/$ [name='gradingtable']
^course/(?P<course_id>\d+)/archive/$ [name='coursearchive']
^course/(?P<course_id>\d+)/mail2all/$ [name='mail2all']
^jobs/$ [name='jobs']
^download/(?P<obj_id>\d+)/(?P<filetype>\w+)/secret=(?P<secret>\w+)$ [name='download_secret']
^download/(?P<obj_id>\d+)/(?P<filetype>\w+)/$ [name='download']
^machine/(?P<machine_id>\d+)/$ [name='machine']
^machines/$ [name='machines']
^settings/$ [name='settings']
^courses/$ [name='courses']
^grappelli/
^login/(?P<backend>[^/]+)/$ [name='begin']
^complete/(?P<backend>[^/]+)/$ [name='complete']
^disconnect/(?P<backend>[^/]+)/$ [name='disconnect']
^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$ [name='disconnect_individual']
^teacher/
^admin/
The current URL, files/testscripts/validate_BiADTr2.zip, didn't match any of these.

**Comment by troeger** [comment] 2015-11-03 16:57
Duplicate of #51, fixed in latest version.

**Closed by troeger** 2015-11-03 16:57 UTC
Labels: duplicate
