### ISSUE TITLE
Change the display name of Test machines from backend.

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#53] opened 2015-10-14 09:22 UTC
In the Dashboard view the Test machines are numbered "Test machine ##" and it is not clear which machine corresponds to which assignment. An informative display name would help, but the nice solution is an hint in the assignment view. A quick fix would be the change option in the backend.

**Comment by troeger** [comment] 2015-10-26 15:02
@thehappyhippo Your patch added the hint link for the students, so is this good enough?

I am asking because unique stable names are more complicated than it sounds:

  * The IP address might be unstable due to DHCP for execution hosts.
  * The host name might be not unique due to VM cloning for execution hosts.

I would argue that we have the choice between UUIDs, enforced naming by the admin or the current solution based on database record IDs.

**Comment by thehappyhippo** [comment] 2015-10-26 16:19
Now its clear for the students that the submissions are tested by which machines. The display name would be a ui feature to have fixed names set in the backend, For example the "GPU machine" or the "big memory machine" etc.

**Comment by troeger** [comment] 2015-10-26 16:25
Ok, sounds like an optional feature that relates to the rendering of test machine names in the frontend. If you don't change the name, it is generated from the ID. We might even use the existing UUID model field for that.

**Comment by troeger** [comment] 2017-12-20 23:19
Duplicate of #201

**Closed by troeger** 2017-12-20 23:19 UTC
Labels: new feature
